Days count wrong when birthday is not a Leap year
slwdc/NICParser pull request #4
Opened 2020-06-18 12:17 UTC by malinga91

2020-06-18 12:20 UTC, malinga91 commented
> Hi @malinga91 - Please feel free to send a Pull-Request.
> 
> In `if (date('L', mktime(0, 0, 0, 1, 1, $year)) == 1) {`, I think it's better to use `if (date('L', mktime(0, 0, 0, 1, 1, $year)) === "1") {` as it provides type safety (even though by context, it should be safe with `==` comparator as well)

2020-07-04 04:39 UTC, Ayesh requested changes
Hi @malinga91 - thanks for submitting changes. 

I marked one line that has a syntax error, which prevents the tests from being run. 
After that, could you please add some tests to make sure the ID numbers are correctly decoded?

Thanks.

2020-07-04 04:39 UTC, Ayesh commented on src/Parser.php
> +    if (date('L', mktime(0, 0, 0, 1, 1, $year)) === "1")
```suggestion
    if (date('L', mktime(0, 0, 0, 1, 1, $year)) === "1") {
```

There is a missing curly brace at the end, which prevents the tests from being run.

2020-07-04 04:39 UTC, Ayesh commented on composer.json
> +    "name": "malinga91/nic-parser",
Please do not change the package namespace.

2020-07-05 16:30 UTC, merged

2020-07-05 17:11 UTC, Ayesh commented
Thanks @malinga91 - I have merged and released `v1.1.0` of the library including your changes.